/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cims;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author Priyan
 */
public class First_Run extends javax.swing.JFrame {

    /**
     * Creates new form First_Run
     */
    public First_Run() {
        initComponents();
        jErrorUserLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCard = new javax.swing.JPanel();
        jWelcomePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jWelcomeNextButton = new javax.swing.JButton();
        jConfigPanel = new javax.swing.JPanel();
        jConfigTestButton = new javax.swing.JButton();
        jConfigBackButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSQLUserNameTextField = new javax.swing.JTextField();
        jSQLPasswordPasswordField = new javax.swing.JPasswordField();
        jCreateAdminPanel = new javax.swing.JPanel();
        jAddUserIdLabel = new javax.swing.JLabel();
        jAddUserIDTextField = new javax.swing.JTextField();
        jAddNameLabel = new javax.swing.JLabel();
        jAddNameTextField = new javax.swing.JTextField();
        jAddContactLabel = new javax.swing.JLabel();
        jAddContactFormattedTextField = new javax.swing.JFormattedTextField();
        jAddEmailLabel = new javax.swing.JLabel();
        jAddEmailTextField = new javax.swing.JTextField();
        jAddPasswordField = new javax.swing.JPasswordField();
        jAddConfirmPasswordField = new javax.swing.JPasswordField();
        jAddConfirmPasswordLabel = new javax.swing.JLabel();
        jAddPasswordLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCreateUserSubmitButton = new javax.swing.JButton();
        jCreateUserButton = new javax.swing.JButton();
        jErrorUserLabel = new javax.swing.JLabel();
        jSuccessPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jFailedPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jCard.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Welcome to CIMS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("This setup will configure the database and check the compatibility of your system");

        jWelcomeNextButton.setText("Next");
        jWelcomeNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWelcomeNextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jWelcomePanelLayout = new javax.swing.GroupLayout(jWelcomePanel);
        jWelcomePanel.setLayout(jWelcomePanelLayout);
        jWelcomePanelLayout.setHorizontalGroup(
            jWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jWelcomePanelLayout.createSequentialGroup()
                .addGroup(jWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jWelcomePanelLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jWelcomePanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jWelcomePanelLayout.createSequentialGroup()
                .addComponent(jWelcomeNextButton)
                .addGap(58, 58, 58))
        );
        jWelcomePanelLayout.setVerticalGroup(
            jWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jWelcomePanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jWelcomeNextButton)
                .addGap(28, 28, 28))
        );

        jCard.add(jWelcomePanel, "welcome");

        jConfigTestButton.setText("Test");
        jConfigTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfigTestButtonActionPerformed(evt);
            }
        });

        jConfigBackButton.setText("Back");
        jConfigBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfigBackButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("SQL User name:");

        jLabel5.setText("SQL Password :");

        javax.swing.GroupLayout jConfigPanelLayout = new javax.swing.GroupLayout(jConfigPanel);
        jConfigPanel.setLayout(jConfigPanelLayout);
        jConfigPanelLayout.setHorizontalGroup(
            jConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConfigPanelLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jConfigBackButton)
                .addGap(40, 40, 40)
                .addComponent(jConfigTestButton)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConfigPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSQLPasswordPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jSQLUserNameTextField))
                .addGap(27, 27, 27))
        );
        jConfigPanelLayout.setVerticalGroup(
            jConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConfigPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSQLUserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSQLPasswordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(jConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConfigTestButton)
                    .addComponent(jConfigBackButton))
                .addGap(28, 28, 28))
        );

        jCard.add(jConfigPanel, "config");

        jAddUserIdLabel.setText("User ID :");

        jAddNameLabel.setText("Name");

        jAddContactLabel.setText("Contact no. :");

        jAddContactFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jAddEmailLabel.setText("e-Mail ID :");

        jAddEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddEmailTextFieldActionPerformed(evt);
            }
        });

        jAddConfirmPasswordLabel.setText("Confirm Password :");

        jAddPasswordLabel.setText("Password :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Create Admin User: ");

        jCreateUserSubmitButton.setText("Submit");
        jCreateUserSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateUserSubmitButtonActionPerformed(evt);
            }
        });

        jCreateUserButton.setText("Clear");

        jErrorUserLabel.setForeground(new java.awt.Color(255, 51, 51));
        jErrorUserLabel.setText("jLabel8");

        javax.swing.GroupLayout jCreateAdminPanelLayout = new javax.swing.GroupLayout(jCreateAdminPanel);
        jCreateAdminPanel.setLayout(jCreateAdminPanelLayout);
        jCreateAdminPanelLayout.setHorizontalGroup(
            jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCreateAdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jCreateAdminPanelLayout.createSequentialGroup()
                            .addGroup(jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jAddNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jAddUserIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jAddNameTextField)
                                .addComponent(jAddUserIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))
                        .addGroup(jCreateAdminPanelLayout.createSequentialGroup()
                            .addGroup(jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jAddContactLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jAddEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jAddPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jAddConfirmPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jAddEmailTextField)
                                .addComponent(jAddContactFormattedTextField)
                                .addComponent(jAddPasswordField)
                                .addComponent(jAddConfirmPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCreateAdminPanelLayout.createSequentialGroup()
                            .addComponent(jCreateUserButton)
                            .addGap(29, 29, 29)
                            .addComponent(jCreateUserSubmitButton)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jErrorUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jCreateAdminPanelLayout.setVerticalGroup(
            jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCreateAdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddUserIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddUserIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddContactFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddConfirmPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jErrorUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jCreateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCreateUserSubmitButton)
                    .addComponent(jCreateUserButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jCard.add(jCreateAdminPanel, "card4");

        jSuccessPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Setup Successful.");
        jSuccessPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 178, 50));

        jButton1.setText("Finish");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jSuccessPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jCard.add(jSuccessPanel, "success");

        jFailedPanel.setForeground(new java.awt.Color(255, 51, 51));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Setup Failed.");

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        jErrorLabel.setText("jLabel8");

        javax.swing.GroupLayout jFailedPanelLayout = new javax.swing.GroupLayout(jFailedPanel);
        jFailedPanel.setLayout(jFailedPanelLayout);
        jFailedPanelLayout.setHorizontalGroup(
            jFailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFailedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFailedPanelLayout.createSequentialGroup()
                        .addGap(0, 198, Short.MAX_VALUE)
                        .addGroup(jFailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFailedPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(164, 164, 164))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFailedPanelLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(208, 208, 208))))
                    .addComponent(jErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jFailedPanelLayout.setVerticalGroup(
            jFailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFailedPanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jErrorLabel)
                .addGap(50, 50, 50)
                .addGroup(jFailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jCard.add(jFailedPanel, "failed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jWelcomeNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWelcomeNextButtonActionPerformed
        // TODO add your handling code here:
        shiftPage("config");
    }//GEN-LAST:event_jWelcomeNextButtonActionPerformed

    private void jConfigBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfigBackButtonActionPerformed
        // TODO add your handling code here:
        shiftPage("welcome");
    }//GEN-LAST:event_jConfigBackButtonActionPerformed

    private void jConfigTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfigTestButtonActionPerformed
        // TODO add your handling code here:
        try{
            String uname = jSQLUserNameTextField.getText();
            String pass = new String(jSQLPasswordPasswordField.getPassword());
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cims",uname,pass);
            Statement smt = con.createStatement();
            smt.executeUpdate("create database "+Constant.database_name+";");
            smt.executeUpdate("create table "+Constant.chemical_table+" (\n" +
                    "casno varchar(200) primary key,\n" +
                    "iname text not null,\n" +
                    "rno int,\n" +
                    "cname text,\n" +
                    "mfor text,\n" +
                    "stype text\n" +
                    ");");
            smt.executeUpdate("create table "+Constant.inventory_table+"(\n" +
                    "botno int primary key,\n" +
                    "casno text not null,\n" +
                    "tid text,\n" +
                    "purdate date,\n" +
                    "expirydate date,\n" +
                    "company text,\n" +
                    "cost int,\n" +
                    "purqty int,\n" +
                    "remqty int,\n" +
                    "borrow bit not null\n" +
                    ");");
            smt.executeUpdate("create table "+Constant.user_table+" (\n" +
                    "uid varchar(200) primary key,\n" +
                    "uname text not null,\n" +
                    "email text not null,\n" +
                    "contact text not null,\n" +
                    "password text not null,\n" +
                    "utype text not null\n" +
                    ");");
            smt.executeUpdate("create table "+Constant.borrow_table+"(\n" +
                    "botno int,\n" +
                    "bid varchar(200),\n" +
                    "bdate date,\n" +
                    "rdate date,\n" +
                    "Primary key (botno,bid)\n" +
                    ");");
            smt.executeUpdate("create table "+Constant.borrow_log_table+"(\n" +
                    "botno int,\n" +
                    "bid varchar(200),\n" +
                    "bdate date,\n" +
                    "rdate date,\n" +
                    "Primary key (botno,bid)\n" +
                    ");");
            smt.executeUpdate("create table "+Constant.inventory_log_table+"(\n" +
                    "botno int primary key,\n" +
                    "casno text not null,\n" +
                    "tid text,\n" +
                    "purdate date,\n" +
                    "expirydate date,\n" +
                    "company text,\n" +
                    "cost int,\n" +
                    "purqty int,\n" +
                    "remqty int,\n" +
                    "borrow bit not null\n" +
                    ");");
            User.addUser("exception", "Admin", "priyanmuthu@gmail.com", "Admin", "7415470018", "noitpecxe");
            CIMS_Preference.setSQL(uname, pass);
            shiftPage("success");
        }catch(Exception e){
            jErrorLabel.setText(""+e);
            shiftPage("failed");
        }
    }//GEN-LAST:event_jConfigTestButtonActionPerformed

    private void jAddEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddEmailTextFieldActionPerformed

    private void jCreateUserSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateUserSubmitButtonActionPerformed
        // TODO add your handling code here:
        String error;
        String userId = jAddUserIDTextField.getText();
        String name = jAddNameTextField.getText();
        String contact = jAddContactFormattedTextField.getText();
        String email = jAddEmailTextField.getText();
        String userType = "Admin";
        String pass = new String(jAddPasswordField.getPassword());
        String confirmPass = new String(jAddConfirmPasswordField.getPassword());
        boolean flag = false;
        error = "Error: Unknown error";
        if(!User.checkUserID(userId)){
            if(User.checkPassword(pass, confirmPass)){
                try{
                    flag = User.addUser(userId, name, email, userType, contact, pass);
                }catch(NumberFormatException e){
                    error = "Error: Contact input mismatch";
                }
                catch(Exception ex){
                    error = "Error: "+ex;
                }

            }
            else{
                error = "Error: Password mismatch";
            }
        }
        else{
            error = "Error: userId exists";
        }
        if(flag){
            shiftPage("success");
        }
        else{
            jErrorUserLabel.setVisible(true);
            jErrorUserLabel.setText(error);
        }
    }//GEN-LAST:event_jCreateUserSubmitButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CIMS_Preference.setfirstRun(true);
        Login.main(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        shiftPage("config");
    }//GEN-LAST:event_jButton3ActionPerformed
    
    void shiftPage(String a){
        CardLayout cl = (CardLayout) jCard.getLayout();
        cl.show(jCard, a);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First_Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First_Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First_Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First_Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First_Run().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jAddConfirmPasswordField;
    private javax.swing.JLabel jAddConfirmPasswordLabel;
    private javax.swing.JFormattedTextField jAddContactFormattedTextField;
    private javax.swing.JLabel jAddContactLabel;
    private javax.swing.JLabel jAddEmailLabel;
    private javax.swing.JTextField jAddEmailTextField;
    private javax.swing.JLabel jAddNameLabel;
    private javax.swing.JTextField jAddNameTextField;
    private javax.swing.JPasswordField jAddPasswordField;
    private javax.swing.JLabel jAddPasswordLabel;
    private javax.swing.JTextField jAddUserIDTextField;
    private javax.swing.JLabel jAddUserIdLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jCard;
    private javax.swing.JButton jConfigBackButton;
    private javax.swing.JPanel jConfigPanel;
    private javax.swing.JButton jConfigTestButton;
    private javax.swing.JPanel jCreateAdminPanel;
    private javax.swing.JButton jCreateUserButton;
    private javax.swing.JButton jCreateUserSubmitButton;
    private javax.swing.JLabel jErrorLabel;
    private javax.swing.JLabel jErrorUserLabel;
    private javax.swing.JPanel jFailedPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jSQLPasswordPasswordField;
    private javax.swing.JTextField jSQLUserNameTextField;
    private javax.swing.JPanel jSuccessPanel;
    private javax.swing.JButton jWelcomeNextButton;
    private javax.swing.JPanel jWelcomePanel;
    // End of variables declaration//GEN-END:variables
}
