/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package cims;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;


/**
 *
 * @author Priyan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    static User user;
    
    public Login() {
        initComponents();
        int h = this.getHeight();
        int w = this.getWidth();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        this.setLocation(x, y);
        resetLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUserIdDispLoginLabel = new javax.swing.JLabel();
        jPasswordDispLabel = new javax.swing.JLabel();
        jUserIdLoginTextField = new javax.swing.JTextField();
        jPasswordLoginPasswordField = new javax.swing.JPasswordField();
        jSubmitLoginBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLoginClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CIMS : Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jUserIdDispLoginLabel.setText("User Id :");

        jPasswordDispLabel.setText("Password :");

        jUserIdLoginTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jUserIdLoginTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jUserIdLoginTextFieldMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jUserIdLoginTextFieldMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jUserIdLoginTextFieldMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jUserIdLoginTextFieldMouseReleased(evt);
            }
        });
        jUserIdLoginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserIdLoginTextFieldActionPerformed(evt);
            }
        });

        jPasswordLoginPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPasswordLoginPasswordFieldMouseEntered(evt);
            }
        });
        jPasswordLoginPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordLoginPasswordFieldActionPerformed(evt);
            }
        });
        jPasswordLoginPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordLoginPasswordFieldKeyReleased(evt);
            }
        });

        jSubmitLoginBut.setText("Login");
        jSubmitLoginBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSubmitLoginBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitLoginButActionPerformed(evt);
            }
        });

        jLabel1.setText("© Product of IIT Indore CSE Batch 2011");

        jLoginClearButton.setText("Clear");
        jLoginClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jUserIdDispLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jUserIdLoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPasswordDispLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordLoginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLoginClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jSubmitLoginBut, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(418, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUserIdDispLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserIdLoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordDispLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordLoginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSubmitLoginBut)
                    .addComponent(jLoginClearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordLoginPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordLoginPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordLoginPasswordFieldActionPerformed

    private void jUserIdLoginTextFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserIdLoginTextFieldMouseReleased
        // TODO add your handling code here:
        String a;
        a=jUserIdLoginTextField.getText();
        if(a.equals("Enter User ID")){
            jUserIdLoginTextField.setText("");
        }
    }//GEN-LAST:event_jUserIdLoginTextFieldMouseReleased

    private void jUserIdLoginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserIdLoginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserIdLoginTextFieldActionPerformed

    private void jUserIdLoginTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserIdLoginTextFieldMouseEntered
        // TODO add your handling code here:
        String a;
        a=jUserIdLoginTextField.getText();
        if(a.equals("Enter User ID")){
            jUserIdLoginTextField.setText("");
        }
    }//GEN-LAST:event_jUserIdLoginTextFieldMouseEntered

    private void jUserIdLoginTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserIdLoginTextFieldMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jUserIdLoginTextFieldMouseExited

    private void jUserIdLoginTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserIdLoginTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserIdLoginTextFieldMousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        String a;
        char c[] = jPasswordLoginPasswordField.getPassword();
        String b  = new String(c);
        a=jUserIdLoginTextField.getText();
        if(a.isEmpty()){
            jUserIdLoginTextField.setText("Enter User ID");
        }
        if(b.isEmpty()){
            jPasswordLoginPasswordField.setText("CodePassword");
        }
    }//GEN-LAST:event_formMousePressed

    private void jPasswordLoginPasswordFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordLoginPasswordFieldMouseEntered
        // TODO add your handling code here:\
        char a[] = jPasswordLoginPasswordField.getPassword();
        String b = new String(a);
        if(b.equals("CodePassword")){
            jPasswordLoginPasswordField.setText("");
        }
    }//GEN-LAST:event_jPasswordLoginPasswordFieldMouseEntered

    private void jSubmitLoginButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitLoginButActionPerformed
        // TODO add your handling code here:
        
        logIn();
        
    }//GEN-LAST:event_jSubmitLoginButActionPerformed

    private void jPasswordLoginPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordLoginPasswordFieldKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            logIn();
        }
    }//GEN-LAST:event_jPasswordLoginPasswordFieldKeyReleased

    private void jLoginClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginClearButtonActionPerformed
        // TODO add your handling code here:
        resetLogin();
    }//GEN-LAST:event_jLoginClearButtonActionPerformed
    
    void resetLogin(){
        jUserIdLoginTextField.setText(null);
        jPasswordLoginPasswordField.setText(null);
    }
    
    static User getLoginUser(){
        return user;
    }
    
    void logIn(){
        String uname = jUserIdLoginTextField.getText();
        String password = new String(jPasswordLoginPasswordField.getPassword());
        if(User.checkUserID(uname)){
            if(User.verifyPassword(uname, password)){
                user = User.logIn(uname, password);
                Home.main(null);
                this.dispose();
            }
            else{
                System.out.println("Password incorrect");
            }
        }
        else{
            System.out.println("User Id doesnt exist");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jLoginClearButton;
    private javax.swing.JLabel jPasswordDispLabel;
    private javax.swing.JPasswordField jPasswordLoginPasswordField;
    private javax.swing.JButton jSubmitLoginBut;
    private javax.swing.JLabel jUserIdDispLoginLabel;
    private javax.swing.JTextField jUserIdLoginTextField;
    // End of variables declaration//GEN-END:variables
}
